### ISSUE TITLE
2019年1月排期表

### ISSUE THREAD

**Issue by leyayun** [FENews/FENews.org#4]
## 一月份

|状态    | 完成日期               | Owner             | 原文 |
| -------- |:-------------:|:--------------:|:-----------:|
|完成 |   2019-01-28  |  @xueqingxiao  | [Trash talk: the Orinoco garbage collector](https://v8.dev/blog/trash-talk) |
|完成 |   2019-01-30  |  @xueqingxiao  | [Why Isn’t X a Hook?](https://overreacted.io/why-isnt-x-a-hook/) |

**Comment by xueqingxiao** [comment]
## 二月份

|状态    | 完成日期               | Owner             | 原文 |
| -------- |:-------------:|:--------------:|:-----------:|
|待完成  |   2019-02-17  |  @xueqingxiao    |[Jank Busters Part One](https://v8.dev/blog/jank-busters) |
