### ISSUE TITLE
FENews相关主题及负责人

### ISSUE THREAD

**Issue by xueqingxiao** [FENews/FENews.org#7]
轮值主席 - @xueqingxiao 
 
顾问 - @danielhe

### 相关主题
- React / Vue / Angular
  - 组长 - @lzbSun 
  - 组员 - @leyayun @itxuye 
- Flluter / RN
  - 组长 - @itxuye 
  - 组员 - @zxy7 @jinrichardJIN 
- Webpack / Parcel / rollup
  - 组长 - @fengshenhai-0727 
  - 组员 - @itxuye @hearingguo 
- Rust / wasm
  - 组长 - @leyayun 
  - 组员 @itxuye 
- V8 / JS
  - 组长 - @xueqingxiao 
  - 组员 - @zxy7 @hearingguo @itxuye 
- deno / typescript
  - 组长 - @jkchao 
  - 组员 - @itxuye @xueqingxiao @zhangxinmei @jinrichardJIN

**Comment by itxuye** [comment]
Webpack / Parcel / rollup
typescript

**Comment by leyayun** [comment]
申请加入 React / Vue / Angular 主题

**Comment by xueqingxiao** [comment]
申请加入deno / typescript

**Comment by hearingguo** [comment]
申请加入：Webpack / Parcel / rollup 和 V8 / JS

**Comment by jinrichardJIN** [comment]
申请 flutter / typescript
